import Vue from 'vue'
import App from './App.vue'
import Instafeed from 'instafeed.js'


Vue.config.productionTip = false


new Vue({
  render: h => h(App),
}).$mount('#app')

fetch('https://api.instagram.com/oembed?url=http://instagr.am/p/fA9uwTtkSN/')
  .then(
    function (response) {
      if (response.status !== 200) {
        console.log('Teve um erro, codigo: ' +
          response.status);
        return;
      }

      // Examine the text in the response
      response.json().then(function (data) {
        console.log(data);
        console.log(data.thumbnail_url);
        document.getElementById('teste').innerHTML = '<img src="' + data.thumbnail_url + '" />'
      });
    }
  )
  .catch(function (err) {
    console.log('Fetch Error :-S', err);
  });


  var userFeed = new Instafeed({
    get: 'user',
    userId: '3158052742',
    accessToken: '3158052742.ddce505.a8cf47107a254f84b76879516940b84c'
  });
  userFeed.run();

  var feed = new Instafeed({
    get: 'user',
    userId: '3158052742',
    template: '<a href="{{link}}"><img class="insta-image" src="{{image}}" /></a>',
    accessToken: '3158052742.ddce505.a8cf47107a254f84b76879516940b84c'
});
feed.run();

 

// Access Code: 3158052742.ddce505.a8cf47107a254f84b76879516940b84c

// Insta Feed

// Generated by CoffeeScript 1.9.3 232192182
